.default: &default
  only:
    - merge_requests
    - web

.default_tag: &default_tag
  tags:
    - backend-docker-large

# Updated by automation script: replaced deprecated runner image : Email Ref [IMP] Deprecating outdated Maven ​Runner Images on July ​14th, 2025
image: docker.phonepe.com/ci/ubuntu/jammy/jdk/openjdk/17/maven/3.9.9:latest

stages:
  - build
  - deploy

"Build Snapshot":
  stage: build
  <<: *default
  <<: *default_tag
  script:
    - mvn package -U -DskipTests=true -Denforcer.skip
  when: manual

"Deploy Snapshot":
  stage: deploy
  <<: *default_tag
  <<: *default
  allow_failure: false
  script:
    - mvn deploy -U -DskipTests=true -Denforcer.skip
  when: manual